AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'notionFromBacklog

  Sample SAM Template for notionFromBacklog

  '
Globals:
  Function:
    Timeout: 3
Parameters:
  apiKey:
    Type: String
  tableId:
    Type: String
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.HelloWorldFunction19d43fc4DepLayer
    Metadata:
      SamResourceId: HelloWorldFunction
  HelloFrontFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloFrontFunction
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        HelloFront:
          Type: Api
          Properties:
            Path: /hello-front
            Method: post
      Environment:
        Variables:
          API_KEY:
            Ref: apiKey
          TABLE_ID:
            Ref: tableId
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.HelloFrontFunctionf0b7d614DepLayer
    Metadata:
      SamResourceId: HelloFrontFunction
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: /Users/katayamayuuki/github/notion-from-backlog/notionFromBacklog/.aws-sam/auto-dependency-layer/adl_nested_template.yaml
    Type: AWS::CloudFormation::Stack
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - HelloWorldFunctionRole
      - Arn
